/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import domainModels.HoaDon;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.PrintJob;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.query.Query;
import services.HoaDonChiTietService;
import services.impl.IManageChiTietHoaDonBanHang;
import utilities.mycompany.DBConext.HibernatUtil;
import viewModel.ViewModelHoaDonChiTietBanHang;

/**
 *
 * @author Admin
 */
public class CreateBill extends javax.swing.JFrame {

    /**
     * Creates new form CreateBill
     */
    private static IManageChiTietHoaDonBanHang cthdService = new HoaDonChiTietService();
    DefaultTableModel model = new DefaultTableModel();
    
    public CreateBill(String id) {
        initComponents();
        setbill(id);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HoaDonBill = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HoaDonBill.setBackground(new java.awt.Color(255, 204, 255));
        HoaDonBill.setBorder(new javax.swing.border.MatteBorder(null));

        bill.setColumns(20);
        bill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bill.setRows(5);
        bill.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane2.setViewportView(bill);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printe_inRaTaiLieu.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HoaDonBillLayout = new javax.swing.GroupLayout(HoaDonBill);
        HoaDonBill.setLayout(HoaDonBillLayout);
        HoaDonBillLayout.setHorizontalGroup(
            HoaDonBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HoaDonBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(HoaDonBillLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HoaDonBillLayout.setVerticalGroup(
            HoaDonBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HoaDonBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HoaDonBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            bill.print();
            this.dispose();
        } catch (PrinterException ex) {
            Logger.getLogger(CreateBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new CreateBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HoaDonBill;
    private javax.swing.JTextArea bill;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

//    private void printBill(JPanel HoaDonBill) {
//        PrinterJob a = PrinterJob.getPrinterJob();
//        a.setJobName("Bill Hóa Đơn Vip Pro");
//
//        a.setPrintable(new Printable() {
//            @Override
//            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
//                pageFormat.setOrientation(PageFormat.LANDSCAPE);
//                if (pageIndex > 0) {
//                    return Printable.NO_SUCH_PAGE;
//                }
//
//                Graphics2D g2 = (Graphics2D) graphics;
//                g2.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
//                g2.scale(0.5, 0.5);
//
//                HoaDonBill.paint(g2);
//
//                return Printable.PAGE_EXISTS;
//            }
//        });
//        boolean b = a.printDialog();
//        if (b) {
//            try {
//                a.print();
//            } catch (Exception e) {
//                System.out.println("error");
//            }
//        }
//    }
    private void setbill(String id) {
        java.util.Date date = java.util.Calendar.getInstance().getTime();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd      hh:mm:ss");
        String tenkh = null;
        String sdt = null;
        String sale = null;
        Session session = HibernatUtil.getFACTORY().openSession();
        Query q = session.createQuery("FROM HoaDon Where Id = '" + id + "' ");
        List<HoaDon> list = q.getResultList();
        for (HoaDon hoaDon : list) {
            tenkh = hoaDon.getIdKhachHang().getTenKhachHang();
            sdt = hoaDon.getIdKhachHang().getSdt();
            if (hoaDon.getIdKhuyenMai() != null) {
                sale = String.valueOf(hoaDon.getIdKhuyenMai().getPhanTramKM());
            }
        }
        
        List<ViewModelHoaDonChiTietBanHang> lisst = cthdService.list(id);
        if (lisst == null) {
            return;
        }
        int tongtien = cthdService.TongTien(id);
        
        String now = format.format(date);
        int i = 1;
        bill.setText(bill.getText() + "===================================================================================");
        bill.setText(bill.getText() + "\n\t\t        \t");
        bill.setText(bill.getText() + "\n\t\t        \t");
        bill.setText(bill.getText() + "\n\t\t        CỬA HÀNG BÁN LẺ ĐỒ GỖ KHÁNH SON\t");
        bill.setText(bill.getText() + "\n\n\t\t\t\t       TIME  :  " + now + "\t");
        bill.setText(bill.getText() + "\n\n\t\t\t                  KHÁCH HÀNG  :  " + tenkh + "\t");
        bill.setText(bill.getText() + "\n\n\t\t\t\t        SDT  :  " + sdt + "\t");
        bill.setText(bill.getText() + "\n\n===================================================================================");
        bill.setText(bill.getText() + "\n\n             STT\t         TÊN SẢN PHẨM\t          SỐ LƯỢNG\t           ĐƠN GIÁ");
        for (ViewModelHoaDonChiTietBanHang a : lisst) {
            bill.setText(bill.getText() + "\n\n               [" + i + "]\t         " + a.getTen() + "  \t                " + a.getSoluong() + "\t\t           " + a.getDonGia() + "");
            i++;
        }
        bill.setText(bill.getText() + "\n\n\n\t\t\t\t\t           SALE :        " + sale);
        bill.setText(bill.getText() + "\n\n\t\t\t\t\t TỔNG TIỀN :        " + tongtien);
        bill.setText(bill.getText() + "\n\n===================================================================================");
        bill.setText(bill.getText() + "\n\n\t\t       CẢM ƠN ĐÃ MUA HÀNG BÊN SHOP\t");
        bill.setText(bill.getText() + "\n\n\t\t" + id + "\t");
        bill.setText(bill.getText() + "\n\n===================================================================================");
        
    }
}
